# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('l', 'Label'), ('v', 'Value')], max_length=1)),
                ('aggfunc', models.CharField(choices=[('s', 'sum'), ('a', 'avg')], max_length=1)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Fields')),
            ],
            options={
                'db_table': 'stat_fields',
            },
        ),
        migrations.CreateModel(
            name='FieldsFill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'stat_fields_fill',
            },
        ),
        migrations.CreateModel(
            name='FieldsValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Fields')),
                ('fields_fill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.FieldsFill')),
            ],
            options={
                'db_table': 'stat_fields_value',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Regions')),
            ],
            options={
                'db_table': 'stat_regions',
            },
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Tables')),
            ],
            options={
                'db_table': 'stat_tables',
            },
        ),
        migrations.AddField(
            model_name='fieldsfill',
            name='redion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Regions'),
        ),
        migrations.AddField(
            model_name='fieldsfill',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Tables'),
        ),
        migrations.AddField(
            model_name='fields',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Tables'),
        ),
    ]
