# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-11 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_remove_fields_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldsfill',
            name='date',
        ),
        migrations.RemoveField(
            model_name='fieldsfill',
            name='redion',
        ),
        migrations.AddField(
            model_name='fieldsfill',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=9),
        ),
        migrations.AddField(
            model_name='fieldsfill',
            name='year',
            field=models.PositiveSmallIntegerField(default=2017),
        ),
        migrations.AddField(
            model_name='fieldsvalue',
            name='region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stats.Regions'),
        ),
        migrations.AddField(
            model_name='regions',
            name='short_name',
            field=models.CharField(default=None, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='fields',
            name='aggfunc',
            field=models.CharField(choices=[('s', 'Сумма'), ('a', 'Среднее значение')], max_length=1),
        ),
    ]
